name: Feature request
description: Request a new feature
title: "<Replace with a short summary of the feature>"
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please consider posting in the New Feature Ideas [issue](https://github.com/kylecorry31/Trail-Sense/issues/2590) or [discussion](https://github.com/kylecorry31/Trail-Sense/discussions/316) instead of logging a new issue. If you do create a new issue, I may modify your description or create my own issue as a replacement to make it easier for development. Please search through existing issues to make sure this isn't a duplicate. By creating this issue, you confirm that you have reviewed and are following the [CONTRIBUTING.md](https://github.com/kylecorry31/Trail-Sense/blob/main/CONTRIBUTING.md) guide. Generative AI use is heavily restricted in this repo, see the [Generative AI section of CONTRIBUTING.md](https://github.com/kylecorry31/Trail-Sense/blob/main/CONTRIBUTING.md#generative-ai) before creating this issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how the new feature will work. Describe how the new feature fits into [Trail Sense's use cases](https://github.com/kylecorry31/Trail-Sense/wiki/Use-Cases) and which tool it should be added to (if applicable).
    validations:
      required: true
    
  - type: textarea
    id: background-info
    attributes:
      label: Background information
      description: Include any background information that may be relevant to the feature request. This may include write-ups, links, algorithms, images, or videos that would be useful in the development of this new feature. If you are suggesting a feature that is mathematical in nature or believe a different algorithm is more accurate, please include trusted sources here so I can cross verify - I try to ensure that all features are backed by research and are well tested using real-world data.
