config:
  validation: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false

complexity:
  LongMethod:
    ignoreAnnotated:
      - 'Composable'
    ignoreFunction:
      - 'update'
      - 'getTool'

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
  PackageNaming:
    active: false
  
orion:
  NoRecursion:
    active: true
