config:
  validation: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    excludeGuardClauses: true

complexity:
  LongMethod:
    ignoreFunction:
      - 'update'
      - 'getTool'
  TooManyFunctions:
    ignorePrivate: true
    ignoreOverridden: true

naming:
  PackageNaming:
    active: false
  
orion:
  NoRecursion:
    active: true
