name: Android Build with SHA256

#支持在子目录构建，需修改后面的代码

on:
  push:
    #branches: [ "main","master","dev","release" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/build.gradle') }}

      - name: Build APKs
        id: build
        #working-directory: android  #android为子目录路径，需修改为您需要的路径
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug assembleRelease

      - name: Generate SHA256 checksums
        #working-directory: android  #android为子目录路径，需修改为您需要的路径
        run: |
          find . -name '*.apk' | while read apk; do
            sha256sum "$apk" > "${apk}.sha256"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build-artifacts
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/debug/*.sha256
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/release/*.sha256
            #android为子目录路径，需修改为您需要的路径
            #android/app/build/outputs/apk/debug/*.apk
            #android/app/build/outputs/apk/debug/*.sha256
            #android/app/build/outputs/apk/release/*.apk
            #android/app/build/outputs/apk/release/*.sha256
            